name: ios_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_icons_flutter: ^2.0.0
  flutter_vector_icons: ^0.1.0
  line_icons: ^0.2.0
  fancy_bottom_navigation: ^0.3.2

  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  json_annotation: ^2.0.0
  page_transition: ^1.1.0
  http: ^0.12.0+2
  flutter_spinkit: "^3.1.0"
  flutter_launcher_icons: "^0.7.2"
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  pk_skeleton: ^0.0.2
  cloud_firestore: ^0.8.2 

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/molecule.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  # flutter_launcher_icons: "^0.7.2"

  # flutter_icons:
  #   ios: true
  #   android: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img_gojek_logo.png 
    - assets/drawer.jpeg
    - assets/icons/icon_menu.png 
    - assets/icons/icon_saldo.png 
    - assets/icons/icon_scan.png 
    - assets/icons/icon_transfer.png 
    - assets/icons/icons-math.png
    - assets/icons/seksa.png


    - assets/images/food_1.jpg
    - assets/images/food_2.jpg
    - assets/images/food_3.jpg
    - assets/images/food_4.jpg
    - assets/images/food_5.jpg
    - assets/images/carel1.jpeg
    - assets/images/carel2.jpeg
    - assets/images/carel3.png
    - assets/images/carel4.png
    - assets/images/carel5.jpg
    - assets/images/carel6.png
    - assets/images/carel7.jpg
    - assets/images/carel8.jpg
    - assets/images/carel9.jpg
    - assets/images/carel10.jpg
    - assets/images/carel11.jpg
    - assets/images/carel12.jpg
    - assets/images/carel13.jpg
    - assets/images/carel14.jpg
    - assets/images/carel15.jpg
    - assets/images/carel16.jpg
    - assets/images/carel17.jpg
    - assets/images/carel18.jpg
    - assets/images/carel19.jpg
    - assets/images/splash.png
    - assets/images/splash.jpg
    - assets/images/molecule.png
    - assets/images/cover.jpg
    - assets/images/user.png
    - assets/images/bg.png
    - assets/data/courses.json


  fonts:
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy-Regular.ttf
    - family: KantumruyBold
      fonts:
        - asset: assets/fonts/Kantumruy-Bold.ttf
          # weight: 700
    - family: NeoSans
      fonts:
        - asset: assets/fonts/NeoSansStd-Regular.otf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/NeoSansStd-Bold.otf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
